apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    app.kubernetes.io/part-of: kcd-sf-26-demo
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
